DECLARE  
 N EMPLOYEE.ENO%TYPE:=&N;
 EN EMPLOYEE.ENAME%TYPE;
S EMPLOYEE.SAL%TYPE;
BEGIN
SELECT ENO,ENAME,SAL INTO N,EN,S FROM EMPLOYEE WHERE ENO=N;
DBMS_OUTPUT.PUT_LINE(N ||'  '||EN||'  '||S);
END; 